services:
  marionette:
    #image: ghcr.io/shniranjan/marionette:latest
    image: marionette:0.9.0 #latest
    container_name: marionette
    ports:
      - 8000:8000
      - 8443:8443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/niranjan/dockerComposer:/stacks
      - /srv/docker_config/marionette/data:/data
      - /srv/docker_config/marionette/certs:/app/certs:ro
    environment:
      - MARIONETTE_PORT=8000
      - MARIONETTE_GATEWAY_PORT=8443
      - RUST_LOG=info
      - MARIONETTE_RELAY_ADDR=0.0.0.0:9121
    restart: unless-stopped
    networks:
      - marionette_marionette-net

networks:
  marionette_marionette-net:
    external: true
