use axum::{
    extract::State,
    http::StatusCode,
    Json,
};
use bollard::container::ListContainersOptions;
use serde::Serialize;
use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;
use std::process::Command;
use std::sync::Arc;

use crate::docker::*;
use crate::models::*;

type ApiResult<T> = Result<Json<T>, (StatusCode, Json<serde_json::Value>)>;

fn error(code: StatusCode, msg: &str) -> (StatusCode, Json<serde_json::Value>) {
    (code, Json(serde_json::json!({"error": msg})))
}

// ── Nginx LB Data Types ──────────────────────────────────────

#[derive(Debug, Clone, Serialize)]
pub struct UpstreamServer {
    pub container_id: String,
    pub container_name: String,
    pub endpoint_id: String,
    pub host: String,
    pub port: u16,
    pub weight: u16,
    pub healthy: bool,
}

#[derive(Debug, Clone, Serialize)]
pub struct Upstream {
    pub domain: String,
    pub path: String,
    pub ssl: bool,
    pub servers: Vec<UpstreamServer>,
    pub config_path: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct LbStatus {
    pub upstreams: Vec<Upstream>,
    pub config_valid: bool,
    pub last_generated: String,
    pub nginx_running: bool,
}

// ── Helpers ──────────────────────────────────────────────────

/// Sanitize a domain name for use as an nginx upstream name.
fn sanitize_name(domain: &str) -> String {
    domain
        .chars()
        .map(|c| if c.is_alphanumeric() || c == '-' { c } else { '_' })
        .collect::<String>()
        .trim_matches('_')
        .to_string()
}

/// Get the nginx upstreams output directory.
fn nginx_dir() -> PathBuf {
    std::env::var("MARIONETTE_NGINX_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from("/etc/nginx/upstreams"))
}

/// Extract the host IP of a container from its network settings.
/// Prefers the bridge network IP, falls back to whatever is available.
fn extract_container_ip(
    inspect: &bollard::models::ContainerInspectResponse,
) -> Option<String> {
    let ns = inspect.network_settings.as_ref()?;
    let networks = ns.networks.as_ref()?;

    // Prefer bridge, then any network
    for net_name in &["bridge", "host"] {
        if let Some(net) = networks.get(*net_name) {
            if let Some(ip) = &net.ip_address {
                if !ip.is_empty() {
                    return Some(ip.clone());
                }
            }
        }
    }

    // Fall back to first network with an IP
    for (_name, net) in networks {
        if let Some(ip) = &net.ip_address {
            if !ip.is_empty() {
                return Some(ip.clone());
            }
        }
    }

    None
}

// ── Config Generation ────────────────────────────────────────

fn generate_upstream_config(upstream: &Upstream) -> String {
    let mut config = format!(
        "# Generated by marionette — {}\nupstream marionette_{} {{\n",
        chrono::Utc::now().to_rfc3339(),
        sanitize_name(&upstream.domain)
    );
    for server in &upstream.servers {
        config.push_str(&format!(
            "    # container: {} ({})\n    server {}:{} weight={} max_fails=3 fail_timeout=30s;\n",
            server.container_name,
            if server.healthy { "healthy" } else { "unhealthy" },
            server.host,
            server.port,
            server.weight,
        ));
    }
    config.push_str("}\n");
    config
}

fn generate_server_block(upstream: &Upstream) -> String {
    let upstream_name = format!("marionette_{}", sanitize_name(&upstream.domain));
    format!(
        "server {{\n    listen {};\n    server_name {};\n\n    location {} {{\n        proxy_pass http://{};\n        proxy_set_header Host $host;\n        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n        proxy_set_header X-Forwarded-Proto $scheme;\n        proxy_read_timeout 60s;\n    }}\n}}\n",
        if upstream.ssl { "443 ssl" } else { "80" },
        upstream.domain,
        upstream.path,
        upstream_name,
    )
}

fn generate_full_config(upstreams: &[Upstream]) -> String {
    let mut config = String::from(
        "# ── Marionette Nginx LB Config ──────────────────────────────\n\
         # Generated by marionette-core\n\
         # DO NOT EDIT MANUALLY — managed by marionette\n\n",
    );

    for upstream in upstreams {
        config.push_str(&generate_upstream_config(upstream));
        config.push('\n');
        config.push_str(&generate_server_block(upstream));
        config.push('\n');
    }

    config
}

// ── Core Discovery Logic ─────────────────────────────────────

#[derive(Debug, Clone)]
struct LabeledContainer {
    endpoint_id: String,
    container_id: String,
    container_name: String,
    labels: HashMap<String, String>,
}

/// Scan all containers across all endpoints for marionette.lb.* labels.
async fn discover_lb_containers(
    state: &Arc<crate::AppState>,
) -> Result<Vec<LabeledContainer>, String> {
    let endpoints_snapshot: Vec<(String, String)> = {
        let eps = state.endpoints.read().await;
        eps.iter()
            .filter(|(_, ep)| matches!(ep.status, EndpointStatus::Connected))
            .map(|(id, ep)| (id.clone(), ep.name.clone()))
            .collect()
    };

    let mut labeled = Vec::new();

    for (endpoint_id, _ep_name) in &endpoints_snapshot {
        let clients = state.clients.read().await;
        let docker = match get_client(endpoint_id, &clients).await {
            Ok(d) => d,
            Err(e) => {
                tracing::warn!("Skipping endpoint {} in LB scan: {}", endpoint_id, e);
                continue;
            }
        };
        drop(clients);

        let containers = docker
            .list_containers::<String>(Some(ListContainersOptions {
                all: false, // only running containers
                ..Default::default()
            }))
            .await
            .map_err(|e| format!("Failed to list containers on {}: {}", endpoint_id, e))?;

        for c in containers {
            let labels = c.labels.unwrap_or_default();
            let enabled = labels
                .get("marionette.lb.enabled")
                .map(|v| v.to_lowercase() == "true")
                .unwrap_or(false);

            if !enabled {
                continue;
            }

            let names = c.names.unwrap_or_default();
            let name = names
                .first()
                .map(|n| n.trim_start_matches('/').to_string())
                .unwrap_or_default();

            labeled.push(LabeledContainer {
                endpoint_id: endpoint_id.clone(),
                container_id: c.id.unwrap_or_default(),
                container_name: name,
                labels,
            });
        }
    }

    Ok(labeled)
}

/// Build the upstream map from labeled containers.
async fn build_upstreams(
    state: &Arc<crate::AppState>,
    containers: &[LabeledContainer],
) -> Result<Vec<Upstream>, String> {
    // Group key: (domain, path)
    let mut groups: HashMap<(String, String), Vec<&LabeledContainer>> = HashMap::new();

    for lc in containers {
        let domain = lc
            .labels
            .get("marionette.lb.domain")
            .cloned()
            .unwrap_or_default();
        let path = lc.labels.get("marionette.lb.path").cloned().unwrap_or_else(|| "/".to_string());

        if domain.is_empty() {
            continue;
        }

        groups.entry((domain, path)).or_default().push(lc);
    }

    let config_dir = nginx_dir();
    let mut upstreams = Vec::new();

    for ((domain, path), group) in groups {
        let ssl = group
            .first()
            .and_then(|lc| lc.labels.get("marionette.lb.ssl"))
            .map(|v| v.to_lowercase() == "true")
            .unwrap_or(false);

        let upstream_name = sanitize_name(&domain);
        let config_path = config_dir
            .join(format!("marionette_{}.conf", upstream_name))
            .to_string_lossy()
            .to_string();

        let mut servers = Vec::new();

        for lc in group {
            let port: u16 = lc
                .labels
                .get("marionette.lb.port")
                .and_then(|v| v.parse().ok())
                .unwrap_or(80);

            let weight: u16 = lc
                .labels
                .get("marionette.lb.weight")
                .and_then(|v| v.parse().ok())
                .unwrap_or(1);

            // Inspect container to get its IP
            let clients = state.clients.read().await;
            let host = match get_client(&lc.endpoint_id, &clients).await {
                Ok(docker) => {
                    drop(clients);
                    match docker.inspect_container(&lc.container_id, None).await {
                        Ok(info) => extract_container_ip(&info).unwrap_or_else(|| "127.0.0.1".to_string()),
                        Err(e) => {
                            tracing::warn!(
                                "Failed to inspect container {}: {}",
                                lc.container_id,
                                e
                            );
                            "127.0.0.1".to_string()
                        }
                    }
                }
                Err(e) => {
                    drop(clients);
                    tracing::warn!("Cannot reach endpoint {}: {}", lc.endpoint_id, e);
                    "127.0.0.1".to_string()
                }
            };

            // Check if container is healthy — simplify: running = healthy
            let healthy = true;

            servers.push(UpstreamServer {
                container_id: lc.container_id.clone(),
                container_name: lc.container_name.clone(),
                endpoint_id: lc.endpoint_id.clone(),
                host,
                port,
                weight,
                healthy,
            });
        }

        upstreams.push(Upstream {
            domain,
            path,
            ssl,
            servers,
            config_path,
        });
    }

    Ok(upstreams)
}

/// Full discovery + build pipeline.
async fn discover_and_build(
    state: &Arc<crate::AppState>,
) -> Result<Vec<Upstream>, (StatusCode, Json<serde_json::Value>)> {
    let containers = discover_lb_containers(state)
        .await
        .map_err(|e| error(StatusCode::INTERNAL_SERVER_ERROR, &e))?;

    build_upstreams(state, &containers)
        .await
        .map_err(|e| error(StatusCode::INTERNAL_SERVER_ERROR, &e))
}

/// Check if nginx is running (pgrep nginx).
fn nginx_running() -> bool {
    Command::new("pgrep")
        .arg("nginx")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// Run nginx -t and return (valid, output).
fn nginx_test() -> (bool, String) {
    match Command::new("nginx").arg("-t").output() {
        Ok(output) => {
            let combined = format!(
                "{}{}",
                String::from_utf8_lossy(&output.stdout),
                String::from_utf8_lossy(&output.stderr)
            );
            (output.status.success(), combined)
        }
        Err(e) => (false, format!("Failed to run nginx -t: {}", e)),
    }
}

/// Run nginx -s reload.
fn nginx_reload() -> (bool, String) {
    match Command::new("nginx").arg("-s").arg("reload").output() {
        Ok(output) => {
            let combined = format!(
                "{}{}",
                String::from_utf8_lossy(&output.stdout),
                String::from_utf8_lossy(&output.stderr)
            );
            (output.status.success(), combined)
        }
        Err(e) => (false, format!("Failed to run nginx -s reload: {}", e)),
    }
}

// ── Endpoints ────────────────────────────────────────────────

/// GET /nginx/upstreams — scan all containers for marionette.lb.* labels,
/// return all discovered upstreams with servers.
pub async fn list_upstreams(
    State(state): State<Arc<crate::AppState>>,
) -> ApiResult<Vec<Upstream>> {
    let upstreams = discover_and_build(&state).await?;
    Ok(Json(upstreams))
}

/// GET /nginx/config — return the full generated nginx config as text.
pub async fn get_config(
    State(state): State<Arc<crate::AppState>>,
) -> Result<String, (StatusCode, String)> {
    let upstreams = discover_and_build(&state)
        .await
        .map_err(|e| (e.0, e.1 .0.get("error").and_then(|v| v.as_str()).unwrap_or("Unknown error").to_string()))?;

    let config = generate_full_config(&upstreams);
    Ok(config)
}

/// POST /nginx/regenerate — scan containers, generate config files,
/// validate config, return LbStatus.
pub async fn regenerate(
    State(state): State<Arc<crate::AppState>>,
) -> ApiResult<LbStatus> {
    let upstreams = discover_and_build(&state).await?;

    // Write config files
    let config_dir = nginx_dir();
    fs::create_dir_all(&config_dir)
        .map_err(|e| error(StatusCode::INTERNAL_SERVER_ERROR, &e.to_string()))?;

    for upstream in &upstreams {
        let config = generate_upstream_config(upstream);
        fs::write(&upstream.config_path, &config)
            .map_err(|e| error(StatusCode::INTERNAL_SERVER_ERROR, &e.to_string()))?;
    }

    // Validate config
    let (config_valid, _test_output) = nginx_test();
    let last_generated = chrono::Utc::now().to_rfc3339();
    let nginx_running = nginx_running();

    // Audit log
    state.audit_log.record(
        "nginx_regenerate",
        "system",
        "nginx_lb",
        &format!(
            "Generated {} upstreams, config valid: {}",
            upstreams.len(),
            config_valid
        ),
        "nginx_lb",
    )
    .await;

    Ok(Json(LbStatus {
        upstreams,
        config_valid,
        last_generated,
        nginx_running,
    }))
}

/// POST /nginx/test — run nginx -t, return { valid, output }.
pub async fn test_config() -> Json<serde_json::Value> {
    let (valid, output) = nginx_test();
    Json(serde_json::json!({
        "valid": valid,
        "output": output,
    }))
}

/// POST /nginx/reload — run nginx -s reload, return { success, output }.
/// Audit logged.
pub async fn reload_nginx(
    State(state): State<Arc<crate::AppState>>,
) -> Json<serde_json::Value> {
    let (success, output) = nginx_reload();

    state
        .audit_log
        .record(
            "nginx_reload",
            "system",
            "nginx_lb",
            &format!("Nginx reload success: {}", success),
            "nginx_lb",
        )
        .await;

    Json(serde_json::json!({
        "success": success,
        "output": output,
    }))
}
